global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'lead-api'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: /actuator/prometheus
  - job_name: 'lead-processor'
    static_configs:
      - targets: ['host.docker.internal:8081']
    metrics_path: /actuator/prometheus